//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarnerhemsEvent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leventsyd_se_dbEntities : DbContext
    {
        public leventsyd_se_dbEntities()
            : base("name=leventsyd_se_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access> access { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<extraproduct> extraproduct { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<package> package { get; set; }
        public virtual DbSet<packproduct> packproduct { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
