//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarnerhemsEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderID { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string deliveryadress { get; set; }
        public Nullable<System.DateTime> eventdate { get; set; }
        public Nullable<int> fk_package_id { get; set; }
        public Nullable<int> fk_extraproduct_id { get; set; }
        public Nullable<int> fk_customer_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual extraproduct extraproduct { get; set; }
        public virtual package package { get; set; }
    }
}
