//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarnerhemsEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodpackdetail
    {
        public int prodpackdetailsID { get; set; }
        public int fk_products_id { get; set; }
        public int fk_package_id { get; set; }
    
        public virtual package package { get; set; }
        public virtual product product { get; set; }
    }
}
